name: dazuoye
channels:
  - defaults
dependencies:
  - pip=20.2.4
  - python=3.8.5
  - setuptools=50.3.1
  - sqlite=3.33.0
  - tk=8.6.10
  - tzdata=2020d
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - pandas=1.0.5
  - jupyter=1.0.0
  - pip:
    - chardet==3.0.4
    - click==7.1.2
    - filelock==3.0.12
    - idna==2.10
    - joblib==0.17.0
    - numpy==1.19.4
    - packaging==20.4
    - protobuf==3.14.0
    - pyparsing==2.4.7
    - regex==2020.11.13
    - requests==2.25.0
    - sacremoses==0.0.43
    - sentencepiece==0.1.91
    - six==1.15.0
    - tokenizers==0.9.3
    - tqdm==4.52.0
    - transformers==3.5.1
    - urllib3==1.26.2
